### PR TITLE
Added New pages

### PR DESCRIPTION
**Pull request by sudiptaexicube**
The 3 new pages added are in the folder /src/pages/  with folders named as 

1. coletaconfirmada
2. ListaCatadores
3. 404

### CODE REVIEW

**Comment by Gpzim98** [comment]
Hi Sudipta.
This code didn't work in my computer, is givin the following error:
Runtime Error
Cannot find module "ionic2-alpha-scroll"

Can you please have a look on this?

**Comment by sudiptaexicube** [comment]
do "npm install" to get the "ionic2-alpha-scroll" installed

**Comment by sudiptaexicube** [comment]
Completed the following pages:

FIRST WAVE
1a) Coleta aberta para coleta confirmada - retorno zap / ligação
1b) Coleta aberta para coleta confirmada - retorno 12h
1c) Lista de Catadores
1d) Coleta confirmada

SECOND WAVE
2a) Coleta Aberta \
2b) Coleta aberta para coleta confirmada - retorno 2 horas \
2c) 404

**Comment by Gpzim98** [comment]
I did npm install and now I am having the following problem:
[20:36:20]  typescript: node_modules/@types/lodash/index.d.ts, line: 19211
            All declarations of 'WeakMap' must have identical type parameters.

Typescript Error
All declarations of 'WeakMap' must have identical type parameters.
node_modules/@types/lodash/index.d.ts
undefined
undefined

**Comment by sudiptaexicube** [comment]
There is a bug in lodash module 

Goto line number **19211** of the file

`node_modules/@types/lodash/index.d.ts`

and change the line to 

`interface WeakMap<K extends object, V> { }`

**Pull request merged**
